services:
  # postgres:
  #   image: postgres:18.6-alpine
  #   container_name: perf-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: perf_db
  #   # ports:
  #   #   - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql
  #     - ./backend-golang-gin/migrations/001_create_products.sql:/docker-entrypoint-initdb.d/001_create_products.sql:ro
  #   networks:
  #     - perf-net
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d perf_db"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  backend-golang-gin:
    build: ./backend-golang-gin
    container_name: backend-golang-gin
    environment:
      APP_PORT: 3000
      DATABASE_URL: postgres://user_test:test123@host.docker.internal:5432/test_db?sslmode=disable
      DB_MAX_OPEN_CONNS: 25
      DB_MAX_IDLE_CONNS: 25
    ports:
      - "3000:3000"
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - perf-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend-rust-actix:
    build: ./backend-rust-actix
    container_name: backend-rust-actix
    environment:
      APP_PORT: 3001
      DATABASE_URL: postgres://user_test:test123@host.docker.internal:5432/test_db?sslmode=disable
      DB_MAX_CONNECTIONS: 25
    ports:
      - "3001:3001"
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - perf-net
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  postgres_data:

networks:
  perf-net:
    driver: bridge
